/**
 * Attestation statement verification, format by format.
 *
 * Every certificate here is generated by openssl at run time rather than
 * checked in as a fixture, for the same reason as `x509.test.ts`: a fixture
 * records what one vendor emitted on one day, and these tests are about what
 * the verifier must accept and — mostly — refuse.
 *
 * The signing is done with `node:crypto`, whose ECDSA output is DER, which is
 * what a real attestation carries and what `verifyWithCertificate` expects.
 * That is a property of the test, not of the library: nothing under `src/` on
 * a ceremony path imports a Node built-in, and `runtime-neutral.test.ts`
 * enforces it.
 */

import { execFileSync } from 'node:child_process';
import { createPrivateKey, sign as nodeSign } from 'node:crypto';
import { mkdtempSync, rmSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import assert from 'node:assert/strict';
import { test, afterAll } from 'vitest';

import { verifyAttestation } from '#internal/server/crypto/attestation.js';
import { parseAuthenticatorData } from '#internal/server/crypto/authenticator-data.js';
import { sha256 } from '#internal/server/crypto/digest.js';
import { COSEAlgorithm } from '#internal/shared/types.js';
import { encodeCBOR, type Encodable } from '#internal/testing/index.js';

const temporary: string[] = [];
afterAll(() => {
  for (const dir of temporary) rmSync(dir, { recursive: true, force: true });
});

function workspace(): string {
  const dir = mkdtempSync(join(tmpdir(), 'passkify-attestation-'));
  temporary.push(dir);
  return dir;
}

interface Key {
  /** PKCS#8 PEM, which both openssl and node:crypto read. */
  pem: string;
  /** Uncompressed EC point: 0x04 || x || y. */
  point: Uint8Array;
  path: string;
}

/** A P-256 key pair, with its public point already unpacked. */
function ecKey(): Key {
  const dir = workspace();
  const path = join(dir, 'key.pem');
  // `ecparam -genkey` rather than `genpkey`: on LibreSSL the latter writes
  // explicit curve parameters into the SPKI, and passkify's X.509 parser only
  // accepts a named-curve OID there. Real attestation certificates always name
  // the curve, so the restriction is the parser being strict, not narrow — but
  // it does mean the fixtures have to be built the way authenticators build
  // them.
  execFileSync('openssl', ['ecparam', '-name', 'prime256v1', '-genkey', '-noout', '-out', path], {
    stdio: 'pipe',
  });
  // The SPKI ends with the uncompressed point, so the tail is x and y.
  const spki = execFileSync('openssl', ['ec', '-in', path, '-pubout', '-outform', 'DER'], {
    stdio: 'pipe',
  });
  const point = new Uint8Array(spki.subarray(spki.length - 65));
  assert.equal(point[0], 0x04, 'expected an uncompressed EC point');
  return { pem: readFileSync(path, 'utf8'), point, path };
}

/** The COSE_Key encoding of an EC2 P-256 public key. */
function coseKey(point: Uint8Array): Uint8Array {
  return encodeCBOR(
    new Map<number, Encodable>([
      [1, 2], // kty: EC2
      [3, COSEAlgorithm.ES256],
      [-1, 1], // crv: P-256
      [-2, point.subarray(1, 33)],
      [-3, point.subarray(33, 65)],
    ]),
  );
}

/** A DER ECDSA signature over `data`, as an authenticator would produce. */
function signDER(key: Key, data: Uint8Array): Uint8Array {
  return new Uint8Array(nodeSign('sha256', data, createPrivateKey(key.pem)));
}

function certificate(options: {
  key: Key;
  subject?: string;
  ca?: boolean;
  days?: number;
  extensions?: string[];
}): Uint8Array {
  const dir = workspace();
  const path = join(dir, 'cert.pem');
  const args = [
    'req',
    '-new',
    '-x509',
    '-key',
    options.key.path,
    '-out',
    path,
    '-days',
    String(options.days ?? 365),
    '-subj',
    options.subject ?? '/CN=passkify attestation',
    '-sha256',
  ];
  if (options.ca) args.push('-addext', 'basicConstraints=critical,CA:TRUE');
  else args.push('-addext', 'basicConstraints=critical,CA:FALSE');
  for (const extension of options.extensions ?? []) args.push('-addext', extension);
  execFileSync('openssl', args, { stdio: 'pipe' });
  return new Uint8Array(
    execFileSync('openssl', ['x509', '-in', path, '-outform', 'DER'], { stdio: 'pipe' }),
  );
}

/**
 * Authenticator data carrying attested credential data, assembled by hand so
 * the credential key is one the test also holds — which the certificate-bound
 * formats need, since they tie the statement to that exact key.
 */
function authenticatorData(cose: Uint8Array, credentialId: Uint8Array) {
  const rpIdHash = new Uint8Array(32).fill(7);
  const aaguid = new Uint8Array(16).fill(9);
  const bytes = new Uint8Array(37 + 16 + 2 + credentialId.length + cose.length);
  bytes.set(rpIdHash, 0);
  bytes[32] = 0x01 | 0x04 | 0x40; // UP | UV | AT
  bytes.set(aaguid, 37);
  bytes[53] = credentialId.length >> 8;
  bytes[54] = credentialId.length & 0xff;
  bytes.set(credentialId, 55);
  bytes.set(cose, 55 + credentialId.length);
  return parseAuthenticatorData(bytes);
}

/** Everything `verifyAttestation` needs, for one freshly-minted credential. */
async function subject() {
  const credentialKey = ecKey();
  const cose = coseKey(credentialKey.point);
  const credentialId = new Uint8Array(16).fill(3);
  const parsed = authenticatorData(cose, credentialId);
  const clientDataHash = await sha256(new TextEncoder().encode('{"type":"webauthn.create"}'));
  const signatureBase = new Uint8Array(parsed.bytes.length + clientDataHash.length);
  signatureBase.set(parsed.bytes, 0);
  signatureBase.set(clientDataHash, parsed.bytes.length);

  return {
    credentialKey,
    base: {
      authenticatorData: parsed,
      clientDataHash,
      credentialPublicKey: cose,
      credentialId,
      aaguid: parsed.attestedCredentialData?.aaguid ?? new Uint8Array(16),
    },
    signatureBase,
  };
}

const statement = (entries: [string, unknown][]) =>
  new Map<string | number, unknown>(entries) as never;

async function rejects(promise: Promise<unknown>, match: RegExp) {
  await assert.rejects(promise, (error: Error) => {
    assert.match(error.message, match);
    return true;
  });
}

// ------------------------------------------------------------------- none

test('"none" accepts an empty statement and refuses a populated one', async () => {
  const { base } = await subject();

  const ok = await verifyAttestation({ ...base, format: 'none', statement: statement([]) });
  assert.equal(ok.type, 'none');
  assert.equal(ok.trusted, false);

  await rejects(
    verifyAttestation({
      ...base,
      format: 'none',
      statement: statement([['sig', new Uint8Array([1])]]),
    }),
    /"none" but the statement is not empty/,
  );
});

// ------------------------------------------------------- unsupported format

test('an unverifiable format is reported when the site asked for no attestation', async () => {
  const { base } = await subject();
  // TPM-backed Windows Hello sends fmt:"tpm" under attestation:"none". Refusing
  // it locked those users out entirely, which is what this guards.
  const result = await verifyAttestation({
    ...base,
    format: 'tpm',
    statement: statement([['ver', '2.0']]),
    requested: 'none',
  });
  assert.equal(result.format, 'tpm');
  assert.equal(result.type, 'none');
  assert.equal(result.trusted, false);
});

test('an unverifiable format throws when the site actually asked for one', async () => {
  const { base } = await subject();
  await rejects(
    verifyAttestation({
      ...base,
      format: 'tpm',
      statement: statement([['ver', '2.0']]),
      requested: 'direct',
    }),
    /not implemented by passkify/,
  );
});

// ----------------------------------------------------------- packed, self

test('packed self-attestation verifies against the credential key', async () => {
  const { credentialKey, base, signatureBase } = await subject();
  const result = await verifyAttestation({
    ...base,
    format: 'packed',
    statement: statement([
      ['alg', COSEAlgorithm.ES256],
      ['sig', signDER(credentialKey, signatureBase)],
    ]),
  });
  assert.equal(result.type, 'self');
  assert.equal(result.trusted, false);
});

test('packed self-attestation refuses an alg that is not the credential key', async () => {
  const { credentialKey, base, signatureBase } = await subject();
  await rejects(
    verifyAttestation({
      ...base,
      format: 'packed',
      statement: statement([
        ['alg', COSEAlgorithm.RS256],
        ['sig', signDER(credentialKey, signatureBase)],
      ]),
    }),
    /alg does not match the credential public key/,
  );
});

test('packed self-attestation refuses a signature over different bytes', async () => {
  const { credentialKey, base } = await subject();
  await rejects(
    verifyAttestation({
      ...base,
      format: 'packed',
      statement: statement([
        ['alg', COSEAlgorithm.ES256],
        ['sig', signDER(credentialKey, new TextEncoder().encode('not the ceremony'))],
      ]),
    }),
    /signature did not verify/,
  );
});

test('packed refuses a statement with no "alg" and one with no "sig"', async () => {
  const { base } = await subject();
  await rejects(
    verifyAttestation({
      ...base,
      format: 'packed',
      statement: statement([['sig', new Uint8Array([1])]]),
    }),
    /missing "alg"/,
  );
  await rejects(
    verifyAttestation({
      ...base,
      format: 'packed',
      statement: statement([['alg', COSEAlgorithm.ES256]]),
    }),
    /missing the "sig" byte string/,
  );
});

// ---------------------------------------------------------- packed, basic

test('packed with a certificate verifies, and is untrusted without roots', async () => {
  const { base, signatureBase } = await subject();
  const attestationKey = ecKey();
  const der = certificate({ key: attestationKey });

  const result = await verifyAttestation({
    ...base,
    format: 'packed',
    statement: statement([
      ['alg', COSEAlgorithm.ES256],
      ['sig', signDER(attestationKey, signatureBase)],
      ['x5c', [der]],
    ]),
  });

  assert.equal(result.type, 'basic');
  // No roots were supplied, so nothing validated the chain. Saying "trusted"
  // here would be the single most misleading thing this function could do.
  assert.equal(result.trusted, false);
  assert.match(result.attestationCertificateSubject ?? '', /CN=passkify attestation/);
});

test('packed with a certificate is trusted when the chain reaches a supplied root', async () => {
  const { base, signatureBase } = await subject();
  const attestationKey = ecKey();
  const der = certificate({ key: attestationKey });

  const result = await verifyAttestation({
    ...base,
    format: 'packed',
    statement: statement([
      ['alg', COSEAlgorithm.ES256],
      ['sig', signDER(attestationKey, signatureBase)],
      ['x5c', [der]],
    ]),
    rootCertificates: [der],
  });
  assert.equal(result.trusted, true);
});

test('packed refuses a CA certificate as the attestation leaf', async () => {
  const { base, signatureBase } = await subject();
  const attestationKey = ecKey();
  await rejects(
    verifyAttestation({
      ...base,
      format: 'packed',
      statement: statement([
        ['alg', COSEAlgorithm.ES256],
        ['sig', signDER(attestationKey, signatureBase)],
        ['x5c', [certificate({ key: attestationKey, ca: true })]],
      ]),
    }),
    /is a CA certificate; it must not be/,
  );
});

/**
 * Rewrite a certificate's validity window into the past.
 *
 * Neither LibreSSL nor OpenSSL 3 will issue an already-expired certificate —
 * `-days` must be positive and `-not_before` does not exist on LibreSSL — so
 * the two UTCTime fields are overwritten in place. They are fixed-width
 * (`17 0d`, thirteen bytes) and the validity is the first UTCTime in a
 * certificate, so the edit needs no ASN.1 surgery and no length fixups.
 *
 * It invalidates the signature, which does not matter and is worth saying why:
 * `verifyAttestation` checks the validity window before it checks the
 * signature, so this reaches the assertion under test and stops there.
 */
function expire(der: Uint8Array): Uint8Array {
  const out = Uint8Array.from(der);
  const stamps = ['200101000000Z', '200102000000Z'];
  let found = 0;
  for (let i = 0; i < out.length - 15 && found < 2; i++) {
    if (out[i] === 0x17 && out[i + 1] === 0x0d) {
      out.set(new TextEncoder().encode(stamps[found]), i + 2);
      found += 1;
      i += 14;
    }
  }
  assert.equal(found, 2, 'expected two UTCTime fields in the validity window');
  return out;
}

test('packed refuses an expired attestation certificate', async () => {
  const { base, signatureBase } = await subject();
  const attestationKey = ecKey();
  const der = expire(certificate({ key: attestationKey }));
  await rejects(
    verifyAttestation({
      ...base,
      format: 'packed',
      statement: statement([
        ['alg', COSEAlgorithm.ES256],
        ['sig', signDER(attestationKey, signatureBase)],
        ['x5c', [der]],
      ]),
    }),
    /expired on/,
  );
});

test('packed refuses a signature made by a key the certificate does not carry', async () => {
  const { base, signatureBase } = await subject();
  const attestationKey = ecKey();
  const impostor = ecKey();
  await rejects(
    verifyAttestation({
      ...base,
      format: 'packed',
      statement: statement([
        ['alg', COSEAlgorithm.ES256],
        ['sig', signDER(impostor, signatureBase)],
        ['x5c', [certificate({ key: attestationKey })]],
      ]),
    }),
    /did not verify against the certificate/,
  );
});

test('packed refuses a malformed x5c', async () => {
  const { base, signatureBase } = await subject();
  const attestationKey = ecKey();
  const sig = signDER(attestationKey, signatureBase);
  await rejects(
    verifyAttestation({
      ...base,
      format: 'packed',
      statement: statement([
        ['alg', COSEAlgorithm.ES256],
        ['sig', sig],
        ['x5c', []],
      ]),
    }),
    /empty or malformed "x5c"/,
  );
  await rejects(
    verifyAttestation({
      ...base,
      format: 'packed',
      statement: statement([
        ['alg', COSEAlgorithm.ES256],
        ['sig', sig],
        ['x5c', [new Uint8Array([1, 2, 3])]],
      ]),
    }),
    /not a parseable X.509 certificate/,
  );
});

// --------------------------------------------------------------- fido-u2f

/**
 * The blob a U2F authenticator signs, which predates authenticator data.
 *
 * `0x00 || rpIdHash || clientDataHash || credentialId || 0x04 || x || y`. The
 * point comes from the key itself rather than being dug back out of the COSE
 * encoding, which is what the verifier does from its side — so agreeing here
 * means agreeing about the format, not about a shared parsing trick.
 */
function u2fData(base: Awaited<ReturnType<typeof subject>>['base'], point: Uint8Array): Uint8Array {
  const out = new Uint8Array(1 + 32 + 32 + base.credentialId.length + point.length);
  let at = 0;
  out[at++] = 0x00;
  out.set(base.authenticatorData.rpIdHash, at);
  at += 32;
  out.set(base.clientDataHash, at);
  at += 32;
  out.set(base.credentialId, at);
  at += base.credentialId.length;
  out.set(point, at);
  return out;
}

test('fido-u2f verifies over the hand-assembled U2F blob', async () => {
  const { credentialKey, base } = await subject();
  const attestationKey = ecKey();
  const result = await verifyAttestation({
    ...base,
    format: 'fido-u2f',
    statement: statement([
      ['sig', signDER(attestationKey, u2fData(base, credentialKey.point))],
      ['x5c', [certificate({ key: attestationKey })]],
    ]),
  });
  assert.equal(result.type, 'basic');
  assert.equal(result.trusted, false);
});

test('fido-u2f requires exactly one certificate', async () => {
  const { credentialKey, base } = await subject();
  const attestationKey = ecKey();
  const der = certificate({ key: attestationKey });
  await rejects(
    verifyAttestation({
      ...base,
      format: 'fido-u2f',
      statement: statement([
        ['sig', signDER(attestationKey, u2fData(base, credentialKey.point))],
        ['x5c', [der, der]],
      ]),
    }),
    /exactly one certificate/,
  );
});

test('fido-u2f refuses a signature over anything but that blob', async () => {
  const { base, signatureBase } = await subject();
  const attestationKey = ecKey();
  await rejects(
    verifyAttestation({
      ...base,
      format: 'fido-u2f',
      // Signing the packed base rather than the U2F one: a plausible mistake,
      // and a forgery if it were accepted.
      statement: statement([
        ['sig', signDER(attestationKey, signatureBase)],
        ['x5c', [certificate({ key: attestationKey })]],
      ]),
    }),
    /signature did not verify/,
  );
});

// ------------------------------------------------------------------ apple

const APPLE_NONCE_OID = '1.2.840.113635.100.8.2';

/** SEQUENCE { [1] { OCTET STRING nonce } }, as Apple's extension carries it. */
function appleNonceExtension(nonce: Uint8Array): string {
  const hex = [...nonce].map((byte) => byte.toString(16).padStart(2, '0'));
  const der = ['30', '24', 'a1', '22', '04', '20', ...hex];
  return `${APPLE_NONCE_OID}=DER:${der.join(':')}`;
}

test('apple accepts a certificate whose nonce and key match the response', async () => {
  const { credentialKey, base, signatureBase } = await subject();
  const nonce = await sha256(signatureBase);
  // Apple's leaf carries the credential's own key, so the certificate is issued
  // from it rather than from a separate attestation key.
  const der = certificate({
    key: credentialKey,
    subject: '/CN=Apple Anonymous Attestation',
    extensions: [appleNonceExtension(nonce)],
  });

  const result = await verifyAttestation({
    ...base,
    format: 'apple',
    statement: statement([['x5c', [der]]]),
  });
  assert.equal(result.type, 'attca');
  assert.equal(result.trusted, false);
});

test('apple refuses a nonce computed over anything else', async () => {
  const { credentialKey, base } = await subject();
  const wrong = await sha256(new TextEncoder().encode('a different ceremony'));
  await rejects(
    verifyAttestation({
      ...base,
      format: 'apple',
      statement: statement([
        ['x5c', [certificate({ key: credentialKey, extensions: [appleNonceExtension(wrong)] })]],
      ]),
    }),
    /nonce does not match/,
  );
});

test('apple refuses a certificate with no nonce extension at all', async () => {
  const { credentialKey, base } = await subject();
  await rejects(
    verifyAttestation({
      ...base,
      format: 'apple',
      statement: statement([['x5c', [certificate({ key: credentialKey })]]]),
    }),
    /no nonce extension/,
  );
});

test('apple refuses a certificate carrying a key that is not the credential', async () => {
  const { base, signatureBase } = await subject();
  const nonce = await sha256(signatureBase);
  // Right nonce, wrong key: the statement is bound to a credential nobody
  // registered, which is exactly the substitution this check exists to stop.
  const impostor = ecKey();
  await rejects(
    verifyAttestation({
      ...base,
      format: 'apple',
      statement: statement([
        ['x5c', [certificate({ key: impostor, extensions: [appleNonceExtension(nonce)] })]],
      ]),
    }),
    /does not match the credential public key/,
  );
});

test('apple requires an x5c at all', async () => {
  const { base } = await subject();
  await rejects(
    verifyAttestation({ ...base, format: 'apple', statement: statement([]) }),
    /requires an x5c chain/,
  );
});
